name: Release

on:
  push:
    tags:
      - 'v[0-9]+*'
  workflow_dispatch:
    tags:
      - 'v[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_XMLDOC_MODE: skip
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '2.0.x'
    - name: Create NuGet package
      run: dotnet pack -c Release ./Mamemaki.EventFlow.Outputs.BigQuery.Storage/Mamemaki.EventFlow.Outputs.BigQuery.Storage.csproj
    - name: Publish nuget
      run: dotnet nuget push ./Mamemaki.EventFlow.Outputs.BigQuery.Storage/bin/Release/Mamemaki.EventFlow.Outputs.BigQuery.Storage.*.nupkg -k "$NUGET_API_KEY" -s https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
